# Use an official Python runtime as a parent image
FROM python:3-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install build dependencies and necessary libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    build-essential \
    python3-dev \
    libffi-dev \
    libssl-dev \
    amd-smi \
    libamd-smi-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install necessary Python packages
RUN pip install --no-cache-dir --no-binary :psutil: psutil nvidia-ml-py openlit

# Expose any required ports, if necessary
EXPOSE 80

# Define default values for the environment variables
ENV GPU_APPLICATION_NAME=default
ENV GPU_ENVIRONMENT=default

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Run the script continuously
CMD ["python", "collector.py"]
