# Use an official Python runtime as a parent image
FROM python:3

# Set the working directory in the container
WORKDIR /usr/src/app

# Install build dependencies and necessary libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    libffi-dev \
    libssl-dev \
    wget \
    && wget https://repo.radeon.com/amdgpu-install/7.1/ubuntu/noble/amdgpu-install_7.1.70100-1_all.deb \
    && apt-get -y install ./amdgpu-install_7.1.70100-1_all.deb \
    && rm amdgpu-install_7.1.70100-1_all.deb \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN amdgpu-install --usecase=rocm -y

RUN cd /opt/rocm/share/amd_smi \
    && python3 -m pip install --upgrade pip \
    && python3 -m pip install --user .

# Install necessary Python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Expose any required ports, if necessary
EXPOSE 80

# Define default values for the environment variables
ENV GPU_APPLICATION_NAME=default
ENV GPU_ENVIRONMENT=default

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Run the script continuously
CMD ["python", "collector.py"]
